<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\js\crear.js" />
    <Content Remove="wwwroot\js\modificar.js" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\js\validacionesUsuarios\crear.js" />
    <None Include="wwwroot\js\validacionesUsuarios\modificar.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccesoADatos\AccesoADatos.csproj" />
    <ProjectReference Include="..\Dto\Dto.csproj" />
    <ProjectReference Include="..\LogicaDeAplicacion\LogicaDeAplicacion.csproj" />
    <ProjectReference Include="..\LogicaDeNegocio\LogicaDeNegocio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Views\AmbosUsuarios\AsignarPuntaje.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="Views\UsuarioDigit\GestionDeDisciplinas.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
